// Code generated by "stringer -type=Protocol -linecomment"; DO NOT EDIT.

package starlight

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PROTOCOL_poll01-10]
	_ = x[PROTOCOL_lpll01-11]
	_ = x[PROTOCOL_hsse01-12]
	_ = x[PROTOCOL_webs01-13]
}

const _Protocol_name = "poll01lpll01hsse01webs01"

var _Protocol_index = [...]uint8{0, 6, 12, 18, 24}

func (i Protocol) String() string {
	i -= 10
	if i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i+10), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
