// Code generated by "stringer -type=sessionState -linecomment"; DO NOT EDIT.

package starlight

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sessionUnknown-0]
	_ = x[sessionEstablished-1]
	_ = x[sessionClosed-2]
}

const _sessionState_name = "unknownestablishedclosed"

var _sessionState_index = [...]uint8{0, 7, 18, 24}

func (i sessionState) String() string {
	if i >= sessionState(len(_sessionState_index)-1) {
		return "sessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sessionState_name[_sessionState_index[i]:_sessionState_index[i+1]]
}
